### ISSUE TITLE
Suggestion: Allow ignoring return value of target method

### ISSUE THREAD

**Issue by Boscop** [chancancode/rust-delegate#10]
I'm using this crate a lot together with the `getset` crate. It generates getters and setters, and I use this crate to delegate many getters/setters to members.
But the problem is that the generated setters return `&mut Self`, for chaining, which I don't need/want, and it makes the signatures that I have to write at every level of delegation very long. (I have several use cases where I have multi-level delegation, multiple layers of composition.)
Please allow ignoring the return type of the delegated function and just using `()` in that case.
E.g. now I have to write this:
```rust
delegate! {
    target self.switcher {
        pub fn set_col(&mut self, col: Col) -> &mut Switcher<AppPage, ConnectedDevice>;

        pub fn set_selected_brightness(&mut self, b: f32) -> &mut Switcher<AppPage, ConnectedDevice>;
    }
}
```
I'd prefer to ignore the return value and just write this:
```rust
delegate! {
    target self.switcher {
        pub fn set_col(&mut self, col: Col);

        pub fn set_selected_brightness(&mut self, b: f32);
    }
}
```
If the parser needs a hint, to know when to insert the extra semicolon,
the syntax could be `;;` (double semicolon at the end), it's also memorable because the return value of the target method gets ignored by inserting an extra semicolon.

The big issue with these setters that return `&mut Self` is that even though I want to allow client-code to set values on my struct's member, I don't want to leak a `&mut` to my member, because then the client-code could mutate/replace it completely!
This problem would also be solved by being able to ignore the return value when delegating.

**Comment by Kobzol** [comment]
I added support for changing the return type in https://github.com/chancancode/rust-delegate/tree/returntype.
You can now either:
1) Omit the return type, which will just execute the function and return `()`
2) Specify a different return type, which will be converted using `.into()`

Please test it if it solves your use case :)

**Comment by Boscop** [comment]
@Kobzol Thanks :)

I just switched to that branch, and this stopped working:
```rust
impl<S: FromPrimitive> Switcher2<S> {
	delegate! {
		target self.switcher {
			pub fn page(&self) -> S;
```
The target method has a generic return type chosen by the caller:
```rust
	pub fn page<T: FromPrimitive>(&self) -> T {
		T::from_usize(self.selected)
	}
```

I get this error:
> error: type annotations needed
error: cannot infer type for `S`

Probably because of calling `.into()` in the generated method. 
I think it should work when calling `Into::<#ret>::into({#body})` where `ret = method.sig.output;`..

**Comment by Kobzol** [comment]
I tried it and it looks like one big headache.

```rust
pub fn page(&self) -> S
{
    Into::<S>::into(self.inner.page())
}
```

Will not work without `self.inner.page::<S>`, but that I cannot really generate generally, because I don't know if the method is generic.

I'm thinking of making the `into` optional, like this:
```rust
fn method(&self) -> u32;

delegate! {
    target self.inner {
        #[into]
        pub(crate) fn method(&self) -> u64;
    }
}
```
to make it simpler and generate the `Into::<...>::into()` machinery only when this opt-in attribute is present.

What do you think?

**Comment by Boscop** [comment]
@Kobzol Yes, I was thinking the same yesterday, it's not possible for rustc to know which source type to use (the T that is `Into<S>` could be some other type than T itself, but if that's a generic (chosen by caller), it's too many degrees of freedom so rustc gives the error). So yes, it's probably the best to make `.into()` optional.
Last night I was thinking about using the syntax `-> ;` for this but that'd be unobvious when someone else (who isn't familiar with this crate) reads it. So yeah, `#[into]` sounds the more reasonable :)

**Comment by Kobzol** [comment]
Ok :) I created a PR for this (https://github.com/chancancode/rust-delegate/pull/11). Please check if `#[into]` works for your use case.

**Comment by Boscop** [comment]
@Kobzol Thanks. I just tested it. It works for the generic case when I omit `#[into]` :)

**Comment by Kobzol** [comment]
I'm not sure.
With `.into()` being optional:
- generic return types work
- if you explicitly change the return type, it will not work

With `.into()` being default:
- generic return types don't work
- if you explicitly change return type, it works out of the box

Maybe it's just a detail, but I feel that it might be better if things "just work" for the default case (so without changed return type).
- if you use the same return type as in the underlying method, it should just work
- if you explicitly opt-in into changing the return type, you also have to opt-in to `#[into]`, because you changed the type anyway, so you also have to tell the macro about it

On the other hand it might be much more common to want to change the return type than to use a generic return type.

A small thing for this crate I suppose, but still something that might be worth thinking about: keeping `into()` optional makes this change backwards-compatible.

**Comment by Boscop** [comment]
Yes, both sides make sense. I do think that it probably occurs more often to want `.into()` than having generic return types chosen by the caller (especially in delegated methods), it's just this particular project that has some special requirements.. (Also GAT workarounds etc.)

**Comment by Kobzol** [comment]
I'm leaning a bit towards the `#[into]` case. We don't have a way of notifying the user about the generic error, since we cannot know if it compiles or not, so he would get a weird compiler error without any explanation. On the other hand changing the return type is an explicit decision, so in that case the user should expect that he has to do something extra to make that work. The delegated methods are anyway usually copy-pasted, so one attribute extra doesn't seem that bad. I'll let this stay opened for a few more days to see if there are any other pboelms and then I'll merge.
