### ISSUE TITLE
is it possible to delegate all methods?

### ISSUE THREAD

**Issue by nikita-skobov** [chancancode/rust-delegate#27]
could I do something like this?

```rust
#[derive(Default, Debug)]
pub struct MetaData {
    data: String,
}

impl MetaData {
    fn metadata_contains(&self, s: &str) -> bool {
        self.data.contains(s)
    }
    fn set_metadata(&mut self, s: &str) {
        self.data = s.to_owned()
    }
}

#[derive(Default, Debug)]
pub struct Data {
    metadata: MetaData,
    data: Vec<u8>
}

impl Data {
    delegate! {
        to self.metadata {
             // without needing to write out
             // each of the methods defined on MetaData
        }
    }
}
```

So then you can do something like:

```rust
let mut data = Data::default();
data.set_metadata("");
```

Without needing to explicitly define set_metadata in the delegate! block of the Data impl.

Is something like this possible?

**Comment by Kobzol** [comment]
It would be great if it were possible, but sadly it is not practically possible right now without some sort of reflection API or without annotating the trait. The problem is that I don't have any robust way of finding the method list of a trait.

What you could do is something like this
```rust
special_trait! {
trait Trait { ... }
}

impl MyStruct {
    delegate! {
          Trait to self.metadata
    }
}
```

But it will only work for traits that you annotate (and not traits from other crates, unless you copy paste them into your code).
If you want this functionality, check out https://lib.rs/crates/ambassador.

**Comment by nikita-skobov** [comment]
ah that makes sense. thanks for the quick response. closing issue :)
