### ISSUE TITLE
`delegate!` macro fails to parse parameters with trailing comma.

### ISSUE THREAD

**Issue by olson-sean-k** [chancancode/rust-delegate#5]
It seems that the `delegate!` macro fails to parse delegate functions when the parameters include a trailing comma. Here's an example:

```rust
impl Delegating {
    delegate! {
        target self.inner {
            pub fn complex_delegated_operation(
                source: SourceParameter,
                destination: DestinationParameter,
                data: Data, // Trailing comma.
            ) -> Result<Data, Error>;
        }
    }
}
```

This is the formatting used by rustfmt for functions that spill over column 100. Removing the trailing comma from `data: Data,` allows `delegate!` to parse, but this is standard Rust syntax and should probably be parsed without errors.

In the debug output, the last parameter is missing from `signature_args`.

**Comment by chancancode** [comment]
Hey, sorry for the late response. I agree this should work!

If someone wants to pick this up, the first step would be to add a test. Then probably something along these lines should do the trick:

1. Make `$rest` optional (`*` instead of `+`) [here](https://github.com/chancancode/rust-delegate/blob/master/src/lib.rs#L797)
2. Add `buffer: { , }` case for `parse_method_args_rest` that is an exact copy of [this](https://github.com/chancancode/rust-delegate/blob/master/src/lib.rs#L835-L856) (alternatively, "consume" the comma there and recurse into `parse_method_args_rest` again with an empty buffer, which should hit the code I linked)

...or rewrite the crate as a procedural macro if you are feeling ambitious 😛
